version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: techuser
      POSTGRES_PASSWORD: techpass
      POSTGRES_DB: techtracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - technology-service
      - project-service
      - analytics-service
      - user-auth-service

  technology-service:
    build: ./technology-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/techtracker
      SPRING_DATASOURCE_USERNAME: techuser
      SPRING_DATASOURCE_PASSWORD: techpass
    depends_on:
      - postgres

  project-service:
    build: ./project-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/techtracker
      SPRING_DATASOURCE_USERNAME: techuser
      SPRING_DATASOURCE_PASSWORD: techpass
    depends_on:
      - postgres

  analytics-service:
    build: ./analytics-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/techtracker
      SPRING_DATASOURCE_USERNAME: techuser
      SPRING_DATASOURCE_PASSWORD: techpass
    depends_on:
      - postgres

  user-auth-service:
    build: ./user-auth-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/techtracker
      SPRING_DATASOURCE_USERNAME: techuser
      SPRING_DATASOURCE_PASSWORD: techpass
    depends_on:
      - postgres

volumes:
  pgdata:
